Models/AppConfigMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppConfigDemo.Models
{
    public class AppConfigMessage
    {
        public string Key { get; set; }
        public string Value { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace AppConfigDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FeatureFlags.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppConfigDemo.Models
{
    public enum FeatureFlags
    {
        AllowDevFeature
    }
}

Models/Settings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppConfigDemo.Models
{
    public class Settings
    {
        public string BackgroundColor { get; set; }
        public long FontSize { get; set; }
        public string FontColor { get; set; }
        public string Message { get; set; }
    }
}

Controllers/DevFeatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppConfigDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.FeatureManagement.Mvc;
using Microsoft.FeatureManagement;

namespace AppConfigDemo.Controllers
{
    [FeatureGate(FeatureFlags.AllowDevFeature)]
    public class DevFeatureController : Controller
    {
        private readonly IFeatureManager _featureManager;

        public DevFeatureController(IFeatureManager featureManager)
        {
            _featureManager = featureManager;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using AppConfigDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Diagnostics;

namespace AppConfigDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly Settings _settings;
        public HomeController(IOptionsSnapshot<Settings> settings)
        {
            _settings = settings.Value;
        }

        public IActionResult Index()
        {
            ViewData["BackgroundColor"] = _settings.BackgroundColor;
            ViewData["FontSize"] = _settings.FontSize;
            ViewData["FontColor"] = _settings.FontColor;
            ViewData["Message"] = _settings.Message;

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AppConfigDemo.Hubs;
using AppConfigDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Azure.EventGrid;
using Microsoft.Azure.EventGrid.Models;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace AppConfigDemo.Controllers
{
    [ApiController]
    [Produces("application/json")]
    public class NotificationHandlerController : Controller
    {
        private readonly IHubContext<NotificationHub> _hubContext;
        private readonly IConfiguration _config;

        public NotificationHandlerController(IHubContext<NotificationHub> hubContext, IConfiguration config)
        {
            _hubContext = hubContext;
            _config = config;
        }

        [HttpPost]
        [Route("api/NotificationHandler")]
        public async Task<IActionResult> Post([FromBody]object request)
        {
            //Deserializing the request 
            EventGridSubscriber eventGridSubscriber = new EventGridSubscriber();

            EventGridEvent[] eventGridEvents = eventGridSubscriber.DeserializeEventGridEvents(request.ToString());


            foreach (EventGridEvent eventGridEvent in eventGridEvents)
            {
                // Validate whether EventType is of "Microsoft.EventGrid.SubscriptionValidationEvent"
                if (eventGridEvent.EventType == "Microsoft.EventGrid.SubscriptionValidationEvent")
                {
                    var eventData = (SubscriptionValidationEventData)eventGridEvent.Data;
                    // Do any additional validation (as required) such as validating that the Azure resource ID of the topic matches
                    // the expected topic and then return back the below response
                    var responseData = new SubscriptionValidationResponse()
                    {
                        ValidationResponse = eventData.ValidationCode
                    };


                    if (responseData.ValidationResponse != null)
                    {

                        return Ok(responseData);
                    }
                }
                else
                {
                    dynamic configMessage = eventGridEvent.Data;

                    string key = configMessage.Key.ToString();

                    if (configMessage.Key == "TestApp:Settings:Message")
                    {
                        var result = await AppConfigConnector.GetValue(key, _config);

                        var message = JsonConvert.DeserializeObject<AppConfigMessage>(result);

                        await _hubContext.Clients.All.SendAsync("SendMessage", message.Value);
                    }
                }
            }

            return Ok();
        }
    }
}

Views/DevFeature/Index.cshtml
@{
    ViewData["Title"] = "Dev Feature";
}
<style>
     body {
        background-color: #ffc34d
    }
    h1 {
        font-size: 58px;
    }
    .marq {
       color: #ffe6ff;
       font-size:32px;
    }
    .img {
        background-color: blue;
        float: right;
    }
</style>

<h1>Index</h1>

<marquee class="marq" bgcolor="Green" direction="left" loop="">
    I am a gud feature. Plz send bacon.
</marquee>

<img resource="/linkthatdoesntwork.jpg" width="500" height="800" class="img"/>
<div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ut posuere risus. Cras lectus eros, mollis ut velit non, porttitor fermentum sapien. Praesent semper leo ut orci condimentum vehicula. Pellentesque ut lobortis tellus. Sed quam arcu, lobortis sed ipsum non, vulputate consectetur ligula. Phasellus egestas cursus erat, sed ornare felis ultricies ac. Cras tristique sem urna, in ultricies ligula venenatis ut. Sed sed tellus in neque iaculis ultricies a sit amet nulla. Etiam scelerisque risus eget vulputate ullamcorper. Duis fringilla ante eu mattis congue. Nunc sapien lorem, rhoncus eu elementum vel, efficitur vitae lacus. Quisque ac eros libero. Aenean eu eleifend justo. Proin eleifend euismod diam, sed tempor sapien imperdiet sit amet. Praesent condimentum volutpat nisi, nec pellentesque est hendrerit dignissim.

    Suspendisse nec lacus quis ligula pretium efficitur. Aliquam ut venenatis justo, ac aliquet ex. Proin suscipit mollis urna eget luctus. Mauris sed velit a orci dictum consectetur. Nullam lacinia erat metus, ac pretium dui consectetur vel. Morbi semper orci eu velit vehicula scelerisque. Integer eleifend mi sapien, non semper ligula fringilla non. Fusce sollicitudin iaculis nibh ullamcorper commodo. Sed dignissim rutrum dolor, non tincidunt lorem pretium vitae.

    In sit amet orci laoreet, rutrum velit nec, bibendum erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi at diam faucibus velit ornare ultricies vel rutrum ipsum. Aliquam blandit vitae elit rhoncus convallis. In at mi augue. Sed felis nunc, consectetur ut lorem vel, ultricies vehicula est. Maecenas non urna tristique, egestas dolor vel, faucibus lectus. Nulla sollicitudin eleifend felis, id luctus tortor. Mauris accumsan eros quis nunc sagittis volutpat id non libero. Duis eget mi pellentesque, aliquet diam ut, condimentum turpis. Mauris turpis mi, feugiat eu nisl ac, fringilla lobortis enim. Vestibulum commodo lacus ac justo aliquet, quis hendrerit nunc mattis.
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    body {
        background-color: @ViewData["BackgroundColor"]
    }
    h1 {
        color: @ViewData["FontColor"];
        font-size: @ViewData["FontSize"];
    }
</style>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h2 id="configMessage">@ViewData["Message"]</h2>
</div>

Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.FeatureManagement.AspNetCore

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppConfigDemo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppConfigDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <feature name="AllowDevFeature">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DevFeature" asp-action="Index">Dev Feature</a>
                            </li>
                        </feature>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - AppConfigDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/lib/aspnet-signalr/signalr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>